version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: location-service-postgres
    environment:
      POSTGRES_DB: location_service_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: location-service-redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: